### Cadastrar uma nova forma de pagamento
POST https://localhost:5001/api/forma-pagamento/create
Content-Type: application/json

{
    "Nome" : "Cartão de Crédito",
    "Ordem": 1
}

### Listar todas as formas de pagamento
GET https://localhost:5001/api/forma-pagamento/list