### Cadastrar um novo item de venda
POST https://localhost:5001/api/item/create
Content-Type: application/json

{
    "ProdutoId" : 2,
    "Quantidade" : 1,
    "Preco" : 3.5,
    "CarrinhoId" : "f34e722e-bb9a-446a-998b-fa080df9ac1d"
}

### Listar todos os itens do carrinho
GET https://localhost:5001/api/item/getbycartid/f34e722e-bb9a-446a-998b-fa080df9ac1d